// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.1
// source: pkg/protocol/protocol.proto

package protocol

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type MessageType int32

const (
	MessageType_MSG_TEXT        MessageType = 0
	MessageType_MSG_JOIN        MessageType = 1
	MessageType_MSG_LEAVE       MessageType = 2
	MessageType_MSG_TYPING      MessageType = 3
	MessageType_MSG_STOP_TYPING MessageType = 4
)

// Enum value maps for MessageType.
var (
	MessageType_name = map[int32]string{
		0: "MSG_TEXT",
		1: "MSG_JOIN",
		2: "MSG_LEAVE",
		3: "MSG_TYPING",
		4: "MSG_STOP_TYPING",
	}
	MessageType_value = map[string]int32{
		"MSG_TEXT":        0,
		"MSG_JOIN":        1,
		"MSG_LEAVE":       2,
		"MSG_TYPING":      3,
		"MSG_STOP_TYPING": 4,
	}
)

func (x MessageType) Enum() *MessageType {
	p := new(MessageType)
	*p = x
	return p
}

func (x MessageType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MessageType) Descriptor() protoreflect.EnumDescriptor {
	return file_pkg_protocol_protocol_proto_enumTypes[0].Descriptor()
}

func (MessageType) Type() protoreflect.EnumType {
	return &file_pkg_protocol_protocol_proto_enumTypes[0]
}

func (x MessageType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MessageType.Descriptor instead.
func (MessageType) EnumDescriptor() ([]byte, []int) {
	return file_pkg_protocol_protocol_proto_rawDescGZIP(), []int{0}
}

type Message struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          MessageType            `protobuf:"varint,1,opt,name=type,proto3,enum=gochat.MessageType" json:"type,omitempty"`
	RoomID        string                 `protobuf:"bytes,2,opt,name=RoomID,proto3" json:"RoomID,omitempty"`
	AuthorID      string                 `protobuf:"bytes,3,opt,name=AuthorID,proto3" json:"AuthorID,omitempty"`
	AuthorName    string                 `protobuf:"bytes,4,opt,name=AuthorName,proto3" json:"AuthorName,omitempty"`
	Content       string                 `protobuf:"bytes,5,opt,name=Content,proto3" json:"Content,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Message) Reset() {
	*x = Message{}
	mi := &file_pkg_protocol_protocol_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Message) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Message) ProtoMessage() {}

func (x *Message) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_protocol_protocol_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Message.ProtoReflect.Descriptor instead.
func (*Message) Descriptor() ([]byte, []int) {
	return file_pkg_protocol_protocol_proto_rawDescGZIP(), []int{0}
}

func (x *Message) GetType() MessageType {
	if x != nil {
		return x.Type
	}
	return MessageType_MSG_TEXT
}

func (x *Message) GetRoomID() string {
	if x != nil {
		return x.RoomID
	}
	return ""
}

func (x *Message) GetAuthorID() string {
	if x != nil {
		return x.AuthorID
	}
	return ""
}

func (x *Message) GetAuthorName() string {
	if x != nil {
		return x.AuthorName
	}
	return ""
}

func (x *Message) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

var File_pkg_protocol_protocol_proto protoreflect.FileDescriptor

const file_pkg_protocol_protocol_proto_rawDesc = "" +
	"\n" +
	"\x1bpkg/protocol/protocol.proto\x12\x06gochat\"\xa0\x01\n" +
	"\aMessage\x12'\n" +
	"\x04type\x18\x01 \x01(\x0e2\x13.gochat.MessageTypeR\x04type\x12\x16\n" +
	"\x06RoomID\x18\x02 \x01(\tR\x06RoomID\x12\x1a\n" +
	"\bAuthorID\x18\x03 \x01(\tR\bAuthorID\x12\x1e\n" +
	"\n" +
	"AuthorName\x18\x04 \x01(\tR\n" +
	"AuthorName\x12\x18\n" +
	"\aContent\x18\x05 \x01(\tR\aContent*]\n" +
	"\vMessageType\x12\f\n" +
	"\bMSG_TEXT\x10\x00\x12\f\n" +
	"\bMSG_JOIN\x10\x01\x12\r\n" +
	"\tMSG_LEAVE\x10\x02\x12\x0e\n" +
	"\n" +
	"MSG_TYPING\x10\x03\x12\x13\n" +
	"\x0fMSG_STOP_TYPING\x10\x04B)Z'github.com/olzhasar/gochat/pkg/protocolb\x06proto3"

var (
	file_pkg_protocol_protocol_proto_rawDescOnce sync.Once
	file_pkg_protocol_protocol_proto_rawDescData []byte
)

func file_pkg_protocol_protocol_proto_rawDescGZIP() []byte {
	file_pkg_protocol_protocol_proto_rawDescOnce.Do(func() {
		file_pkg_protocol_protocol_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pkg_protocol_protocol_proto_rawDesc), len(file_pkg_protocol_protocol_proto_rawDesc)))
	})
	return file_pkg_protocol_protocol_proto_rawDescData
}

var file_pkg_protocol_protocol_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_pkg_protocol_protocol_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_pkg_protocol_protocol_proto_goTypes = []any{
	(MessageType)(0), // 0: gochat.MessageType
	(*Message)(nil),  // 1: gochat.Message
}
var file_pkg_protocol_protocol_proto_depIdxs = []int32{
	0, // 0: gochat.Message.type:type_name -> gochat.MessageType
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_pkg_protocol_protocol_proto_init() }
func file_pkg_protocol_protocol_proto_init() {
	if File_pkg_protocol_protocol_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pkg_protocol_protocol_proto_rawDesc), len(file_pkg_protocol_protocol_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_pkg_protocol_protocol_proto_goTypes,
		DependencyIndexes: file_pkg_protocol_protocol_proto_depIdxs,
		EnumInfos:         file_pkg_protocol_protocol_proto_enumTypes,
		MessageInfos:      file_pkg_protocol_protocol_proto_msgTypes,
	}.Build()
	File_pkg_protocol_protocol_proto = out.File
	file_pkg_protocol_protocol_proto_goTypes = nil
	file_pkg_protocol_protocol_proto_depIdxs = nil
}
